_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 1de606ae-5692-49d4-a1f9-6ab4be34df4d
name: Innoraft
mail: tirupati.singh@innoraft.com
slogan: ''
page:
  403: /node/48
  404: /node/49
  front: /node/21
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
